### ISSUE TITLE
Build issue updating to Golang 1.7

### ISSUE THREAD

**Issue by abgordon** [hypriot/rpi-golang#2]
Attempting to build the base image using go 1.7 from the makefile fails with error. This is from branch https://github.com/hypriot/rpi-golang/pull/1 attempting to bump the go version 

Andrew Mon Mar 20 19:47:13 rpi-golang: make build
docker build -t hypriot/rpi-golang:1.7.5 .
Sending build context to Docker daemon 1.079 MB
Step 1 : FROM resin/rpi-raspbian:wheezy
# Executing 1 build trigger...
Step 1 : RUN echo $'WARNING: Systemd is not available on this base image! \nSystemd was included in Debian wheezy as a technology preview. Therefore, we do not install systemd on wheezy images and INITSYSTEM will not work.'
 ---> Using cache
 ---> 6ec77fbbb6a1
Step 2 : FROM hypriot/rpi-golang:1.4.2
 ---> 07ee5159ddd3
Step 3 : MAINTAINER Dieter Reuter <dieter@hypriot.com>
 ---> Using cache
 ---> 34feb4f212f9
Step 4 : RUN apt-get update && apt-get install -y     ca-certificates     gcc     libc6-dev     make     git     --no-install-recommends &&     rm -rf /var/lib/apt/lists/*
 ---> Using cache
 ---> 9ccda55046df
Step 5 : ENV GOROOT_BOOTSTRAP /goroot
 ---> Using cache
 ---> 82d667351edf
Step 6 : ENV GOLANG_VERSION 1.7.5
 ---> Using cache
 ---> 492aaba42a30
Step 7 : ADD ./etc/services /etc/services
 ---> Using cache
 ---> eb8f05ef13f8
Step 8 : RUN mkdir -p /goroot1.7.5 &&     git clone https://go.googlesource.com/go /goroot1.7.5 &&     cd /goroot1.7.5 &&     git checkout go$GOLANG_VERSION &&     cd /goroot1.7.5/src &&     GOARM=6 ./all.bash
 ---> Running in 43ec25409619
Cloning into '/goroot1.7.5'...
Checking out files: 100% (6441/6441), done.
Note: checking out 'go1.7.5'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b new_branch_name

HEAD is now at 753452f... [release-branch.go1.7] go1.7.5
##### Building Go bootstrap tool.
cmd/dist
fatal error: rt_sigaction failure

runtime stack:
runtime.throw(0x531425)
	/goroot/src/runtime/panic.go:491 +0xa4
runtime.setsig(0x40, 0xa65e8, 0x54da01)
	/goroot/src/runtime/os_linux.c:302 +0xa8
runtime.initsig()
	/goroot/src/runtime/signal_unix.c:39 +0x88
mstart()
	/goroot/src/runtime/proc.c:856 +0x6c
runtime.mstart()
	/goroot/src/runtime/proc.c:836 +0x4c

goroutine 1 [runnable]:
runtime.main()
	/goroot/src/runtime/proc.go:16
runtime.goexit()
	/goroot/src/runtime/asm_arm.s:1322 +0x4
The command '/bin/sh -c mkdir -p /goroot1.7.5 &&     git clone https://go.googlesource.com/go /goroot1.7.5 &&     cd /goroot1.7.5 &&     git checkout go$GOLANG_VERSION &&     cd /goroot1.7.5/src &&     GOARM=6 ./all.bash' returned a non-zero code: 2
make: *** [build] Error 2

**Comment by cceckman** [comment]
It looks like there's official images for non-x86 architectures now: 
https://github.com/docker-library/official-images#architectures-other-than-amd64
Maybe this just needs to point to - I think https://hub.docker.com/r/arm32v7/golang/ is the right one?

**Comment by StefanScherer** [comment]
Please use the official golang image as it is now multi-arch and just work on ARM.
